# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1444614560);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1444614680);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444617799);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1444614439);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1444614319);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1444614800);
user_pref("browser.cache.disk.capacity", 266240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/odroid/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.blocked", "{\"Fay6Z6Xp85eCE8Gvl6A8og==\":1,\"wCjKaWnnuolY21o7O+SZqg==\":1}");
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "ID");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150918101134");
user_pref("browser.slowStartup.averageTime", 5937);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150918101134");
user_pref("browser.startup.homepage_override.mstone", "41.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0,\"bookmarks\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1444614144198");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1444614149219");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1444700549219");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1443404903300");
user_pref("datareporting.policy.firstRunTime", "1443175752457");
user_pref("datareporting.sessions.current.activeTicks", 691);
user_pref("datareporting.sessions.current.firstPaint", 6489);
user_pref("datareporting.sessions.current.main", 2704);
user_pref("datareporting.sessions.current.sessionRestored", 7494);
user_pref("datareporting.sessions.current.startTime", "1444614075413");
user_pref("datareporting.sessions.current.totalTime", 4765);
user_pref("datareporting.sessions.currentIndex", 22);
user_pref("datareporting.sessions.prunedIndex", 21);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"41.0\",\"DEVTOOLS_OS_ENUMERATED_PER_USER\":\"41.0\",\"DEVTOOLS_OS_IS_64_BITS_PER_USER\":\"41.0\",\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"41.0\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"41.0\"}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 11);
user_pref("extensions.blocklist.pingCountVersion", 11);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1444614561);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150902.02");
user_pref("extensions.lastAppVersion", "41.0");
user_pref("extensions.lastPlatformVersion", "41.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"33.0\",\"st\":1443229352000,\"mt\":1442577252000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"33.0\",\"st\":1442579513000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"33.0\",\"st\":1442579513000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"2.9\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20150918101134");
user_pref("gecko.mstone", "41.0");
user_pref("idle.lastDailyNotification", 1444619014);
user_pref("media.gmp-manager.buildID", "20150918101134");
user_pref("media.gmp-manager.lastCheck", 1444614143);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1444011620);
user_pref("places.history.expiration.transient_current_max_pages", 19658);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1443405453);
user_pref("toolkit.startup.last_success", 1444614078);
user_pref("toolkit.telemetry.cachedClientID", "b0675f54-7703-4199-8de0-7d762844929e");
user_pref("toolkit.telemetry.previousBuildID", "20141013200607");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
